PXC-4407: PXC 8.0.37 refresh - Q2 2024 (Fix gcc-13 errors)
https://perconadev.atlassian.net/browse/PXC-4407

Description
-----------
Server compilation fails with gcc-13 due to nonnull-compare of `this`
pointer in the WSREP(THD) macro.

  sql/binlog.cc: In member function ‘int THD::decide_logging_format(Table_ref*)’:
  sql/binlog.cc:10730:47: error: ‘nonnull’ argument ‘this’ compared to NULL [-Werror=nonnull-compare]

We get this error when `this` pointer is compared with NULL when
Werror=nonnull-compare is specified.

Solution
--------
Occurences of `WSREP(this)` have been replaced with `WSREP_NNULL(this)`.